FROM node:18-alpine

RUN apk add --no-cache libc6-compat
RUN npm --version

RUN addgroup --system --gid 1001 treeco
RUN adduser --system --uid 1001 treeco

RUN mkdir /app
WORKDIR /app
RUN mkdir /imagens

COPY ./servico /app
RUN rm /app/package-lock.json
RUN rm /app/node_modules -rf
RUN npm install

RUN chown -R treeco:treeco /app/src
RUN chown -R treeco:treeco /imagens
