version: '3.3'

services:
  servico:
    image: treeco/servico
    container_name: servico
    build: 
      dockerfile: ./Dockerfile.servico
      context: .
    ports:
      - '3001:3000'
    volumes:
      - ./servico:/app
      - ./imagens:/imagens
    command: /app/start.sh
    depends_on:
      - banco
      - imagens

  banco:
    image: treeco/banco
    container_name: banco
    build: 
      dockerfile: ./Dockerfile.banco
      context: .
    hostname: banco
    volumes:
      - ./banco:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: 'treeco'
      POSTGRES_PASSWORD: 'FaGQFchCiSh4Cce3JjucFiu5z5ybtytm!'
    ports:
      - '3002:5432'

  imagens:
    image: treeco/imagens
    container_name: imagens
    build: 
      dockerfile: ./Dockerfile.imagens
      context: .
    hostname: imagens
    volumes:
      - './imagens:/usr/share/nginx/html'
    ports:
      - '3003:80'
    expose:
      - '3003'
