version: '3.3'

services:
  servico:
    image: treeco/servico
    container_name: servico
    build: ./dockerfiles/servico
    ports:
      - '3001:3000'
    expose:
      - '3001'      
    command: /app/start.sh
    depends_on:
      - banco
      - imagens

  banco:
    image: treeco/banco
    container_name: banco
    hostname: banco
      
  imagens:
    image: treeco/imagens
    build: ./dockerfiles/imagens/
    hostname: imagens
    container_name: imagens
    ports:
      - '3003:80'
    expose:
      - '3003'
